---
- name: Restart "mysql"
  systemd:
    daemon_reload: "yes"
    name: "mysql"
    state: "restarted"
    enabled: "yes"

- name: Setup MySQL
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/
  environment:
    PATH: "/home/isucon/local/go/bin:/home/isucon/local/node/bin:/home/isucon/local/ruby/bin:/home/isucon/local/python/bin:/home/isucon/local/perl/bin:/home/isucon/local/php/bin:/home/isucon/.cargo/bin:/home/isucon/.deno/bin:/home/isucon/bin:/home/isucon/.local/bin:/usr/bin:/sbin:/bin"
  shell: |
    mysql -u isucon -pisucon xsuportal < webapp/sql/schema.sql

#- name: allow access from webapp
#  become: yes
#  become_user: isucon
#  shell: |
#    mysql -u isucon -pisucon -e "GRANT ALL PRIVILEGES ON *.* TO isucon@'54.95.216.196' IDENTIFIED BY 'isucon' WITH GRANT OPTION;"
