# FIXME: changeme for new setup.
---
#- name: Build Web Application Go
#  become: yes
#  become_user: isucon
#  args:
#    chdir: /home/isucon/osu_sample/webapp/go/
#  environment:
#    PATH: "/home/isucon/local/go/bin:/home/isucon/local/node/bin:/home/isucon/local/ruby/bin:/home/isucon/local/python/bin:/home/isucon/local/perl/bin:/home/isucon/local/php/bin:/home/isucon/.cargo/bin:/home/isucon/.deno/bin:/home/isucon/bin:/home/isucon/.local/bin:/usr/bin:/sbin:/bin"
#  shell: |
#    make osu_sample

- name:  Set env
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/webapp/golang
  command: set -o allexport; source ~isucon/env; set +o allexport

- name: Build Web Application Go
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/webapp/golang
#  environment:
#    PATH: "/home/isucon/local/go/bin:/home/isucon/local/node/bin:/home/isucon/local/ruby/bin:/home/isucon/local/python/bin:/home/isucon/local/perl/bin:/home/isucon/local/php/bin:/home/isucon/.cargo/bin:/home/isucon/.deno/bin:/home/isucon/bin:/home/isucon/.local/bin:/usr/bin:/sbin:/bin"
  shell: make

- name: Copy Service file
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - xsuportal-api-go.service
    - xsuportal-api-web.service

#- name: Copy GCP credentials file
#  copy:
#    src: "gcp_credentials.json"
#    dest: "/home/gcp_credentials.json"
#    owner: "root"
#    group: "root"
#    mode: "0644"
